apiVersion: skaffold/v1
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:
    - image: farberg/popular-slides
      context: web-app

    - image: farberg/popular-slides-spark
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
