apiVersion: skaffold/v1
kind: Config

metadata:
  name: sentiment

build:
  artifacts:
    - image: csv-producer-image
      context: csv-producer

    #- image: farberg/popular-slides-spark
    #  context: spark-app
    
    - image: spark-consumer-image
      context: spark-consumer

    - image: dashboard
      context: dashboard

    - image: ngx
      context: static

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
