apiVersion: skaffold/v1
kind: Config

metadata:
  name: sentiment

build:
  artifacts:
    - image: farberg/popular-slides-spark
      context: spark-app

    - image: dashboard
      context: dashboard

    - image: ngx
      context: static

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
