#Begin: Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |
    CREATE TABLE `sentence` (
      `id` SMALLINT unsigned  NOT NULL,
      `person` VARCHAR(50) NOT NULL,
      `n_serie`  tinyint NOT NULL,
      `n_season`  tinyint NOT NULL,
      `sentence`  VARCHAR(5000),
      `sentiment`  tinyint,
      PRIMARY KEY (`id`)
    );

    CREATE TABLE `sentiment_counts` (
      `person` VARCHAR(50) NOT NULL,
      `n_season`  tinyint NOT NULL,
      `sentiment_group_n2`  BIGINT,
      `sentiment_group_n1`  BIGINT,
      `sentiment_group_p1`  BIGINT,
      `sentiment_group_p2`  BIGINT,
       PRIMARY KEY (`person`,`n_season`)
    );

    DELIMITER //
      CREATE PROCEDURE add_count(
        IN per VARCHAR(50), 
        IN season tinyint, 
        IN sen_gp_n2 BIGINT,
        IN sen_gp_n1 BIGINT,
        IN sen_gp_p1 BIGINT,
        IN sen_gp_p2 BIGINT)
      BEGIN
        INSERT INTO sentiment_counts (
          person,
          n_season,
          sentiment_group_n2,
          sentiment_group_n1,
          sentiment_group_p1,
          sentiment_group_p2)
        VALUES (per,season,sen_gp_n2,sen_gp_n1,sen_gp_p1,sen_gp_p2)
        ON DUPLICATE KEY UPDATE
          sentiment_group_n2 = sen_gp_n2,
          sentiment_group_n1 = sen_gp_n1,
          sentiment_group_p1 = sen_gp_p1,
          sentiment_group_p2 = sen_gp_p2;
      END //
    DELIMITER ;

    CREATE VIEW allSeasons AS SELECT DISTINCT n_season FROM sentence;
    CREATE VIEW allPeople AS SELECT DISTINCT person FROM sentence;
    CREATE VIEW allPeopleChart AS SELECT person, SUM(sentiment_group_n2) AS n2, SUM(sentiment_group_n1) AS n1, SUM(sentiment_group_p1) AS p1, SUM(sentiment_group_p2) AS p2 FROM sentiment_counts GROUP BY person;
    CREATE VIEW allSeasonsChart AS SELECT n_season, SUM(sentiment_group_n2) AS n2, SUM(sentiment_group_n1) AS n1, SUM(sentiment_group_p1) AS p1, SUM(sentiment_group_p2) AS p2 FROM sentiment_counts GROUP BY n_season;

    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (1,'waymar royce',1,1,'What d’you expect? They’re savages One lot steals a goat from another lot and before you know it, they’re ripping each other to pieces');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (2,'will',1,1,'I’ve never seen wildlings do a thing like this I’ve never seen a thing like this, not ever in my life');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (3,'waymar royce',1,1,'How close did you get?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (4,'will',1,1,'Close as any man would');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (5,'gared',1,1,'We should head back to the wall');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (6,'royce',1,1,'Do the dead frighten you?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (7,'gared',1,1,'Our orders were to track the wildlings We tracked them They won’t trouble us no more');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (8,'royce',1,1,'You don’t think he’ll ask us how they died? Get back on your horse');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (9,'will',1,1,'Whatever did it to them could do it to us They even killed the children');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (10,'royce',1,1,'It’s a good thing we’re not children You want to run away south, run away Of course, they will behead you as a deserter If I don’t catch you first Get back on your horse I won’t say it again');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (11,'royce',1,1,'Your dead men seem to have moved camp');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (12,'will',1,1,'They were here');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (13,'gared',1,1,'See where they went');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (14,'royce',1,1,'What is it?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (15,'gared',1,1,'It’s');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (16,'jon',1,1,'Go on Father’s watching');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (17,'jon',1,1,'And your mother');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (18,'septa mordane',1,1,'Fine work, as always Well done');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (19,'sansa',1,1,'Thank you');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (20,'septa mordane',1,1,'I love the detail that you’ve managed to get in this corners Quite beautiful the stitching');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (21,'ned',1,1,'And which one of you was a marksman at ten? Keep practicing, Bran Go on');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (22,'jon',1,1,'Don’t think too much, Bran');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (23,'robb',1,1,'Relax your bow arm JON');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (24,'robb',1,1,'Quick, Bran, faster');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (25,'cassel',1,1,'Lord Stark My lady A guardsman just rode in from the hills They’ve captured a deserter from the Night’s Watch');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (26,'ned',1,1,'Get the lads to saddle their horses');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (27,'catelyn',1,1,'Do you have to?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (28,'ned',1,1,'He swore an oath, Cat');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (29,'cassel',1,1,'The law is law, my lady');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (30,'ned',1,1,'Tell Bran he’s coming, too');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (31,'catelyn',1,1,'Ned Ten is too young to see such things');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (32,'ned',1,1,'He won’t be a boy forever And winter is coming');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (33,'robb',1,1,'Lad, go run back and get the rest');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (34,'will',1,1,'White Walkers I saw the White Walkers White Walkers The White Walkers, I saw them');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (35,'will',1,1,'I know I broke my oath And I know I’m a deserter I should have gone back to the Wall and warned them But I saw what I saw I saw the White Walkers People need to know If you can get word to my family, tell them I’m no coward Tell them I’m sorry');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (36,'will',1,1,'Forgive me, lord');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (37,'ned',1,1,'In the name of Robert of the House Baratheon, first of his name');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (38,'jon',1,1,'Don’t look away');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (39,'ned',1,1,'King of the Andals and the First Men');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (40,'jon',1,1,'Father will know if you do');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (41,'ned',1,1,'Lord of the Seven Kingdoms and protector of the realm, I, Eddard of the House Stark, Lord of Winterfell and Warden of the North, sentence you to die');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (42,'jon',1,1,'You did well');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (43,'ned',1,1,'You understand why I did it?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (44,'bran',1,1,'Jon said he was a deserter');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (45,'ned',1,1,'But do you understand why I had to kill him?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (46,'bran',1,1,'Our way is the old way?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (47,'ned',1,1,'The man who passes the sentence should swing the sword');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (48,'bran',1,1,'Is it true he saw the White Walkers?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (49,'ned',1,1,'The White Walkers have been gone for thousands of years');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (50,'bran',1,1,'So he was lying?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (51,'ned',1,1,'A madman sees what he sees');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (52,'jon',1,1,'What is it?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (53,'theon',1,1,'Mountain lion?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (54,'ned',1,1,'There are no mountain lions in these woods');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (55,'theon',1,1,'It’s a freak');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (56,'ned',1,1,'It’s a direwolf');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (57,'ned',1,1,'Tough old beast');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (58,'robb',1,1,'There are no direwolves south of the Wall');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (59,'jon',1,1,'Now there are five');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (60,'jon',1,1,'You want to hold it?');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (61,'bran',1,1,'Where will they go? Their mother’s dead');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (62,'cassel',1,1,'They don’t belong down here');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (63,'ned',1,1,'Better a quick death They won’t last without their mother');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (64,'theon',1,1,'Right Give it here');
    INSERT INTO sentence (id, person, n_serie, n_season, sentence) VALUES (65,'bran',1,1,'NO');
    
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('bran',1,1500,2500,3000,3000);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('ned',1,2545,1254,2356,4521);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('jon',1,1243,1232,2500,1588);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('cassel',1,800,200,250,1000);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES('theon',1,3500,2500,1500,500);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES('catelyn',1,1452,2145,2541,1100);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('bran',2,1500,2500,3000,500);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('ned',2,2545,1254,2356,500);
    INSERT INTO sentiment_counts (person, n_season, sentiment_group_n2,sentiment_group_n1,sentiment_group_p1,sentiment_group_p2) VALUES ('jon',2,1243,1232,2500,500);
    CALL add_count('cassel',2,800,200,250,500);
    CALL add_count('theon',2,3500,2500,1500,500);
    CALL add_count('catelyn',2,1452,2145,2541,500);


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      containers:
        - name: my-mysql
          image: mysql
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "sentence"
          ports:
            - containerPort: 33060
          # Mount the volume
          # Mount configmap at expected location (excerpt)
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
#End: Service
